# Generated by Django 5.2.5 on 2025-08-19 06:07

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="author",
            fields=[
                ("author", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="member",
            fields=[
                ("member_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=80)),
                ("join_Date", models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name="books",
            fields=[
                ("book_id", models.AutoField(primary_key=True, serialize=False)),
                ("book_title", models.CharField(max_length=50)),
                ("category", models.CharField(max_length=50)),
                ("is_available", models.BooleanField(default=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="book.author"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BorrowedRecords",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issue_date", models.DateField(default=datetime.date.today)),
                ("due_date", models.DateField()),
                ("return_date", models.DateField(null=True)),
                ("fine", models.FloatField(default=0)),
                (
                    "book_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="book.books"
                    ),
                ),
                (
                    "member_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="book.member"
                    ),
                ),
            ],
        ),
    ]
