# Generated by Django 5.2.5 on 2025-08-19 07:40

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="borrowedrecords",
            name="book_id",
        ),
        migrations.RemoveField(
            model_name="borrowedrecords",
            name="member_id",
        ),
        migrations.RenameField(
            model_name="author",
            old_name="author",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="member",
            old_name="member_id",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="member",
            old_name="join_Date",
            new_name="join_date",
        ),
        migrations.AlterField(
            model_name="member",
            name="email",
            field=models.EmailField(max_length=80, unique=True),
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=50)),
                ("category", models.CharField(max_length=50)),
                ("is_available", models.BooleanField(default=True)),
                (
                    "issue_date",
                    models.DateField(
                        blank=True, default=datetime.date.today, null=True
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("return_date", models.DateField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="book.author"
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="book.member",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="books",
        ),
        migrations.DeleteModel(
            name="BorrowedRecords",
        ),
    ]
