# Generated by Django 5.2.5 on 2025-08-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0002_remove_borrowedrecords_book_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="borrowed_books",
            field=models.IntegerField(default=0),
        ),
    ]
