# Generated by Django 5.2.5 on 2025-08-20 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0003_member_borrowed_books"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="issue_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
